// packages/reactui/src/pages/settings/sections/environment/InfoDisplayItem.tsx
import type { ReactNode } from "react"
import { cn } from "@/lib/utils"
import { Alert, AlertDescription } from "@/components/ui/alert"

interface InfoDisplayItemProps {
    label: string
    value: ReactNode
    className?: string
    hasError?: boolean
    errorMessages?: string | string[]
}

export function InfoDisplayItem({
    label,
    value,
    className = "",
    hasError = false,
    errorMessages = [],
}: InfoDisplayItemProps) {
    const messageErrorArray = Array.isArray(errorMessages)
        ? errorMessages
        : (errorMessages ? [errorMessages] : [])
    const valueStyles = hasError
        ? "border-error text-error bg-error/10"
        : "border-base-300 text-base-foreground bg-base-200"

    return (
        <div className="space-y-1.5">
            <div className="flex items-center justify-between gap-4">
                <span className="text-sm font-medium text-base-foreground">
                    {label}
                </span>
                <span
                    className={cn(
                        "text-sm font-mono px-2 py-1 rounded border min-h-[2rem] flex items-center justify-end",
                        valueStyles,
                        className
                    )}
                >
                    {value}
                </span>
            </div>
            {hasError && messageErrorArray.length > 0 && (
                <Alert variant="error" className="mt-2">
                    <AlertDescription className="space-y-1">
                        {messageErrorArray.map((message) => (
                            <p key={message}>{message}</p>
                        ))}
                    </AlertDescription>
                </Alert>
            )}
        </div>
    )
}

// packages/vueui/src/components/settings/InfoDisplayItem.vue
<script setup lang="ts">
import { computed } from 'vue';
import { cn } from '@/lib/utils';

const props = withDefaults(
  defineProps<{
    label: string;
    value?: string;
    hasError?: boolean;
    errorMessages?: string | string[];
    class?: string;
  }>(),
  { value: '', hasError: false, errorMessages: () => [], class: '' }
);

const errorArray = computed(() =>
  Array.isArray(props.errorMessages)
    ? props.errorMessages
    : props.errorMessages
      ? [props.errorMessages]
      : []
);
</script>

<template>
  <div class="space-y-1.5">
    <div class="flex items-center justify-between gap-4">
      <span class="text-sm font-medium text-base-foreground">{{ label }}</span>
      <span
        :class="
          cn(
            'text-sm font-mono px-2 py-1 rounded border min-h-[2rem] flex items-center justify-end',
            hasError
              ? 'border-error text-error bg-error/10'
              : 'border-base-300 text-base-foreground bg-base-200',
            props.class
          )
        "
      >
        <slot>{{ value }}</slot>
      </span>
    </div>
    <div
      v-if="hasError && errorArray.length"
      class="mt-2 p-3 rounded-md bg-error/10 border border-error text-error text-sm"
    >
      <p v-for="(msg, i) in errorArray" :key="i" class="mb-1 last:mb-0">
        {{ msg }}
      </p>
    </div>
  </div>
</template>
