// packages/reactui/src/pages/projects/components/CreateProjectDialog.tsx
import React, { useState, useEffect } from 'react';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

interface CreateProjectDialogProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    onCreate: (projectName: string) => Promise<void>;
    isCreating?: boolean;
    error?: string | null;
}

export const CreateProjectDialog: React.FC<CreateProjectDialogProps> = ({
    open,
    onOpenChange,
    onCreate,
    isCreating = false,
    error,
}) => {
    const [projectName, setProjectName] = useState('');

    useEffect(() => {
        if (open) {
            setProjectName('');
        }
    }, [open]);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        if (projectName.trim()) {
            await onCreate(projectName.trim());
        }
    };

    const isValid = projectName.trim().length > 0;

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="sm:max-w-[425px]">
                <DialogHeader>
                    <DialogTitle>Create New Project</DialogTitle>
                    <DialogDescription>
                        Enter a name for your new project. You'll be asked to choose where to save it.
                    </DialogDescription>
                </DialogHeader>
                <form onSubmit={handleSubmit}>
                    <div className="grid gap-4 py-4">
                        <div className="grid gap-2">
                            <Label htmlFor="project-name">Project Name</Label>
                            <Input
                                id="project-name"
                                value={projectName}
                                onChange={(e) => setProjectName(e.target.value)}
                                placeholder="MyProject"
                                disabled={isCreating}
                                autoFocus
                            />
                            {error && (
                                <p className="text-sm text-error mt-1">{error}</p>
                            )}
                        </div>
                    </div>
                    <DialogFooter>
                        <Button
                            type="button"
                            variant="outline"
                            onClick={() => onOpenChange(false)}
                            disabled={isCreating}
                        >
                            Cancel
                        </Button>
                        <Button
                            type="submit"
                            disabled={!isValid || isCreating}
                        >
                            {isCreating ? 'Creating...' : 'Create'}
                        </Button>
                    </DialogFooter>
                </form>
            </DialogContent>
        </Dialog>
    );
};

// packages/vueui/src/components/CreateProjectDialog.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import Dialog from '@/components/ui/Dialog.vue';
import DialogHeader from '@/components/ui/DialogHeader.vue';
import DialogTitle from '@/components/ui/DialogTitle.vue';
import DialogDescription from '@/components/ui/DialogDescription.vue';
import DialogFooter from '@/components/ui/DialogFooter.vue';
import Button from '@/components/ui/Button.vue';
import Input from '@/components/ui/Input.vue';
import Label from '@/components/ui/Label.vue';

const props = withDefaults(
  defineProps<{
    open: boolean;
    onCreate: (projectName: string) => Promise<void>;
    isCreating?: boolean;
    error?: string | null;
  }>(),
  { isCreating: false, error: null }
);

const emit = defineEmits<{ 'update:open': [value: boolean] }>();

const projectName = ref('');

watch(
  () => props.open,
  (isOpen) => {
    if (isOpen) projectName.value = '';
  }
);

function close() {
  emit('update:open', false);
}
</script>

<template>
  <Dialog :open="open" @update:open="emit('update:open', $event)">
    <DialogHeader>
      <DialogTitle>Create New Project</DialogTitle>
      <DialogDescription>
        Enter a name for your new project. You'll be asked to choose where to save it.
      </DialogDescription>
    </DialogHeader>
    <form
      class="grid gap-4 py-4"
      @submit.prevent="projectName.trim() && onCreate(projectName.trim())"
    >
      <div class="grid gap-2">
        <Label for="create-project-name">Project Name</Label>
        <Input
          id="create-project-name"
          v-model="projectName"
          type="text"
          placeholder="MyProject"
          :disabled="isCreating"
        />
        <p v-if="error" class="text-sm text-error">{{ error }}</p>
      </div>
      <DialogFooter>
        <Button type="button" variant="outline" :disabled="isCreating" @click="close">
          Cancel
        </Button>
        <Button
          type="submit"
          :disabled="!projectName.trim() || isCreating"
        >
          {{ isCreating ? 'Creating...' : 'Create' }}
        </Button>
      </DialogFooter>
    </form>
  </Dialog>
</template>
