// packages/reactui/src/ideCore/IdeCoreProvider.tsx
import React, { useRef } from 'react';
import { IdeCoreContext } from './IdeCoreContext';
import { createEditorRuntime } from './createEditorRuntime';
import { createLocalStorageStoragePort } from './storageAdapter';

interface IdeCoreProviderProps {
    children: React.ReactNode;
}

export const IdeCoreProvider: React.FC<IdeCoreProviderProps> = ({ children }) => {
    const runtimeRef = useRef<ReturnType<typeof createEditorRuntime> | null>(null);
    if (!runtimeRef.current) {
        runtimeRef.current = createEditorRuntime({
            storage: createLocalStorageStoragePort(),
        });
    }
    const runtime = runtimeRef.current;

    return (
        <IdeCoreContext.Provider value={runtime}>
            {children}
        </IdeCoreContext.Provider>
    );
};

// packages/vueui/src/components/IdeCoreProvider.vue
<script setup lang="ts">
import { provide, ref } from 'vue';
import { createEditorRuntime } from '@/runtime/createEditorRuntime';
import { createLocalStorageStoragePort } from '@/runtime/storageAdapter';
import { RUNTIME_KEY } from '@/composables/useIdeCore';

const runtimeRef = ref<ReturnType<typeof createEditorRuntime> | null>(null);
if (!runtimeRef.value) {
  runtimeRef.value = createEditorRuntime({
    storage: createLocalStorageStoragePort(),
  });
}
provide(RUNTIME_KEY, runtimeRef.value);
</script>

<template>
  <slot></slot>
</template>
