// packages/reactui/src/pages/projects/components/RecentProjects.tsx
import React from 'react';
import { IoFolderOpen } from 'react-icons/io5';
import { Card, CardContent } from '@/components/ui/card';

export const RecentProjects: React.FC = () => {
    return (
        <div>
            <h3 className="text-xl font-semibold mb-6 text-base-foreground">
                Recent Projects
            </h3>
            
            <Card className="bg-base-100 border-base-300">
                <CardContent className="py-12 text-center">
                    <div className="w-16 h-16 mx-auto mb-4 rounded-full flex items-center justify-center bg-muted">
                        <IoFolderOpen className="w-8 h-8 text-muted-foreground" />
                    </div>
                    <p className="text-sm text-muted-foreground">
                        No recent projects found. Create a new project to get started.
                    </p>
                </CardContent>
            </Card>
        </div>
    );
};

// vueui/src/components/projects/RecentProjects.vue
<script setup lang="ts">
import Card from '@/components/ui/Card.vue';
import CardContent from '@/components/ui/CardContent.vue';
import { FolderOpen } from '@lucide/vue';
</script>

<template>
  <div>
    <h3 class="text-xl font-semibold mb-6 text-base-foreground">Recent Projects</h3>
    <Card>
      <CardContent class="py-12 text-center">
        <div class="w-16 h-16 mx-auto mb-4 rounded-full flex items-center justify-center bg-base-300">
          <FolderOpen class="size-8 text-muted-foreground" />
        </div>
        <p class="text-sm text-muted-foreground">
          No recent projects found. Create a new project to get started.
        </p>
      </CardContent>
    </Card>
  </div>
</template>
