// vueui/src/components/editor/CommonFieldsForm.vue
<script setup lang="ts">
import EditorFormSection from './EditorFormSection.vue';
import InputEditorItem from './InputEditorItem.vue';

/**
 * Minimal shape for the selected object in the editor (from tree).
 * Avoids depending on @zernikalos/zernikalos in vueui.
 */
export interface ZObjectFormShape {
  refId: string;
  name: string;
  type: { name: string } | string;
  transform: {
    position: { x: number; y: number; z: number };
    rotation: { w: number; x: number; y: number; z: number };
    scale: { x: number; y: number; z: number };
  };
}

defineProps<{
  zObject: ZObjectFormShape;
  notifyChange: () => void;
}>();

function typeDisplayName(t: ZObjectFormShape['type']): string {
  if (typeof t === 'string') return t.charAt(0).toUpperCase() + t.slice(1).toLowerCase();
  return t.name.charAt(0).toUpperCase() + t.name.slice(1).toLowerCase();
}

function updateName(zObject: ZObjectFormShape, value: string, notify: () => void) {
  (zObject as unknown as Record<string, unknown>).name = value;
  notify();
}
</script>

<template>
  <EditorFormSection title="ZObject Properties" badge="3D Object">
    <template #icon>
      <div class="w-4 h-4 rounded border border-current opacity-80" />
    </template>
    <InputEditorItem
      id="refId"
      label="Reference ID"
      :model-value="zObject.refId"
      read-only
      disabled
    />
    <InputEditorItem
      id="type"
      label="Type"
      :model-value="typeDisplayName(zObject.type)"
      read-only
      disabled
    />
    <InputEditorItem
      id="name"
      label="Name"
      :model-value="zObject.name"
      placeholder="Enter object name"
      @update:model-value="(v) => updateName(zObject, v, notifyChange)"
    />
  </EditorFormSection>
</template>

// packages/reactui/src/pages/editor/EditorForm/CommonFieldsForm.tsx
import React from 'react';
import type { UseFormRegister } from 'react-hook-form';
import { zernikalos } from '@/lib/zernikalos';
import { EditorFormSection } from './EditorFormSection';
import { InputEditorItem } from './EditorFormItems';
import { ObjectTypeIcon } from '../components/ObjectTypeIcon';
import { Box } from 'lucide-react';

interface FormData {
    name: string;
    transform: {
        position: { x: number; y: number; z: number };
        rotation: { w: number; x: number; y: number; z: number };
        scale: { x: number; y: number; z: number };
    };
}

interface CommonFieldsFormProps {
    zObject: zernikalos.objects.ZObject;
    register: UseFormRegister<FormData>;
}

export const CommonFieldsForm: React.FC<CommonFieldsFormProps> = ({ zObject, register }) => {
    return (
        <EditorFormSection 
            title="ZObject Properties" 
            icon={<Box className="w-4 h-4" />}
            badge="3D Object"
        >
            <InputEditorItem
                id="refId"
                label="Reference ID"
                value={zObject.refId}
                readOnly
                disabled
            />
            
            <InputEditorItem
                id="type"
                label="Type"
                value={zObject.type.name.charAt(0).toUpperCase() + zObject.type.name.slice(1).toLowerCase()}
                readOnly
                disabled
                icon={<ObjectTypeIcon type={zObject.type as any} size={16} />}
            />
            
            <InputEditorItem
                id="name"
                label="Name"
                register={register('name')}
                placeholder="Enter object name"
            />
        </EditorFormSection>
    );
};
