// packages/vueui/src/components/editor/MathInputEditorItem.vue
<script setup lang="ts">
import Label from '@/components/ui/Label.vue';
import Input from '@/components/ui/Input.vue';
import { computed } from 'vue';

export type MathType = 'vec2' | 'vec3' | 'vec4' | 'quat' | 'euler' | 'rgba';

const props = withDefaults(
  defineProps<{
    id: string;
    label?: string;
    type: MathType;
    namePrefix: string;
    modelValue: Record<string, number>;
    readOnly?: boolean;
    disabled?: boolean;
    class?: string;
    orientation?: 'columns' | 'rows';
  }>(),
  { readOnly: false, disabled: false, orientation: 'columns' }
);

const emit = defineEmits<{ 'update:modelValue': [value: Record<string, number>] }>();

const componentLabels: Record<MathType, string[]> = {
  vec2: ['X', 'Y'],
  vec3: ['X', 'Y', 'Z'],
  vec4: ['X', 'Y', 'Z', 'W'],
  quat: ['W', 'X', 'Y', 'Z'],
  euler: ['X', 'Y', 'Z'],
  rgba: ['R', 'G', 'B', 'A'],
};

const componentKeys: Record<MathType, string[]> = {
  vec2: ['x', 'y'],
  vec3: ['x', 'y', 'z'],
  vec4: ['x', 'y', 'z', 'w'],
  quat: ['w', 'x', 'y', 'z'],
  euler: ['x', 'y', 'z'],
  rgba: ['r', 'g', 'b', 'a'],
};

const labels = componentLabels[props.type];
const keys = componentKeys[props.type];

function updateKey(key: string, value: number) {
  const next = { ...props.modelValue, [key]: value };
  emit('update:modelValue', next);
}

function onInput(key: string, e: Event) {
  const target = (e.target as HTMLInputElement);
  const num = Number(target?.value);
  if (!Number.isNaN(num)) updateKey(key, num);
}

const inputClass = computed(() => {
  const base =
    'text-center rounded-l-none px-3 py-2 text-sm font-mono transition-all duration-200 appearance-none [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none';
  const muted = props.disabled || props.readOnly ? 'bg-base-200' : '';
  const custom = props.class ?? '';
  return [muted, base, custom].filter(Boolean).join(' ');
});
</script>

<template>
  <div :class="orientation === 'rows' ? 'space-y-1' : 'space-y-3'">
    <Label
      v-if="label"
      :for="id"
      class="text-sm font-medium text-base-foreground/90 flex items-center gap-2"
    >
      <div class="w-2 h-2 rounded-full bg-primary/60" />
      {{ label }}
    </Label>
    <div
      :class="
        orientation === 'columns' ? 'flex gap-3' : 'flex flex-col gap-2'
      "
    >
      <div
        v-for="(key, index) in keys"
        :key="key"
        :class="orientation === 'columns' ? 'flex-1 min-w-0' : 'w-full'"
      >
        <div class="flex items-stretch w-full group">
          <span
            class="px-2 py-2 bg-base-300 text-base-foreground border border-base-300 rounded-l-md text-xs font-semibold select-none flex items-center justify-center w-8 transition-all duration-200"
          >
            {{ labels[index] }}
          </span>
          <Input
            :id="`${id}-${key}`"
            type="number"
            step="any"
            :value="modelValue[key]"
            :readonly="readOnly"
            :disabled="disabled"
            :class="inputClass"
            @input="onInput(key, $event)"
          />
        </div>
      </div>
    </div>
  </div>
</template>

// packages/reactui/src/pages/editor/EditorForm/MathInputEditorItem.tsx
import React from 'react';
import { useFormContext } from 'react-hook-form';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

type MathType = 'vec2' | 'vec3' | 'vec4' | 'quat' | 'euler' | 'rgba';

interface MathInputEditorItemProps {
    id: string;
    label: string;
    type: MathType;
    namePrefix: string;
    readOnly?: boolean;
    disabled?: boolean;
    className?: string;
    orientation?: 'columns' | 'rows';
}

const getComponentLabels = (type: MathType): string[] => {
    switch (type) {
        case 'vec2':
            return ['X', 'Y'];
        case 'vec3':
            return ['X', 'Y', 'Z'];
        case 'vec4':
            return ['X', 'Y', 'Z', 'W'];
        case 'quat':
            return ['W', 'X', 'Y', 'Z'];
        case 'euler':
            return ['X', 'Y', 'Z'];
        case 'rgba':
            return ['R', 'G', 'B', 'A'];
        default:
            return [];
    }
};

const getComponentKeys = (type: MathType): string[] => {
    switch (type) {
        case 'vec2':
            return ['x', 'y'];
        case 'vec3':
            return ['x', 'y', 'z'];
        case 'vec4':
            return ['x', 'y', 'z', 'w'];
        case 'quat':
            return ['w', 'x', 'y', 'z'];
        case 'euler':
            return ['x', 'y', 'z'];
        case 'rgba':
            return ['r', 'g', 'b', 'a'];
        default:
            return [];
    }
};

export const MathInputEditorItem: React.FC<MathInputEditorItemProps> = ({
    id,
    label,
    type,
    namePrefix,
    readOnly = false,
    disabled = false,
    className,
    orientation = 'columns'
}) => {
    const { register } = useFormContext();

    const componentLabels = getComponentLabels(type);
    const componentKeys = getComponentKeys(type);

    // Automatically apply bg-muted when disabled or readOnly
    const inputClassName = disabled || readOnly
        ? `bg-muted ${className || ''}`.trim()
        : className;

    const containerClassName = orientation === 'columns' ? 'flex gap-2' : 'flex flex-col gap-2';
    const itemWrapperClassName = orientation === 'columns' ? 'flex-1' : 'w-full';

    return (
        <div className="space-y-2">
            <Label htmlFor={id}>{label}</Label>
            <div className={containerClassName}>
                {componentKeys.map((key, index) => (
                    <div key={key} className={itemWrapperClassName}>
                        <div className="flex items-stretch w-full">
                            <span className="px-2 py-1.5 bg-muted border border-input rounded-l-md text-xs font-medium text-muted-foreground select-none flex items-center justify-center min-w-8">
                                {componentLabels[index]}
                            </span>
                            <Input
                                id={`${id}-${key}`}
                                type="number"
                                step="any"
                                inputMode="decimal"
                                { ...register(`${namePrefix}.${key}`, { valueAsNumber: true }) }
                                readOnly={readOnly}
                                disabled={disabled}
                                className={`${inputClassName ? inputClassName + ' ' : ''}text-center rounded-l-none appearance-none [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none`}
                            />
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
};
