// packages/vueui/src/components/ui/Input.vue
<script setup lang="ts">
import { cn } from '@/lib/utils';

const props = defineProps<{ class?: string; type?: string }>();
</script>

<template>
  <input
    :type="props.type ?? 'text'"
    data-slot="input"
    :class="
      cn(
        'flex h-9 w-full min-w-0 rounded-md border border-base-300 bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm',
        'focus-visible:border-primary focus-visible:ring-primary/50 focus-visible:ring-[3px]',
        'placeholder:text-neutral hover:bg-base-200/50 focus:bg-base-100',
        props.class
      )
    "
    v-bind="$attrs"
  />
</template>

// packages/reactui/src/components/ui/input.tsx
import * as React from 'react';

import { cn } from '@/lib/utils';

function Input({ className, type, ...props }: React.ComponentProps<'input'>) {
    return (
        <input
            type={type}
            data-slot="input"
            className={cn(
                'file:text-base-foreground placeholder:text-neutral-foreground selection:bg-primary selection:text-primary-foreground dark:bg-base-200/30 border-base-300 flex h-9 w-full min-w-0 rounded-md border bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm',
                'focus-visible:border-primary focus-visible:ring-primary/50 focus-visible:ring-[3px]',
                'aria-invalid:ring-error/20 dark:aria-invalid:ring-error/40 aria-invalid:border-error',
                'hover:bg-base-200/50 focus:bg-base-100',
                className
            )}
            {...props}
        />
    );
}

export { Input };
