// vueui/src/components/settings/SettingsFieldInput.vue
<script setup lang="ts">
import Input from '@/components/ui/Input.vue';
import SettingsFieldBase from './SettingsFieldBase.vue';
</script>

<template>
  <SettingsFieldBase
    :title="title"
    :description="description"
    :layout="layout"
  >
    <div class="flex items-center gap-3">
      <Input
        :type="type"
        :min="min"
        :max="max"
        :value="String(value)"
        :placeholder="placeholder"
        :class="inputClass"
        @input="(e: Event) => $emit('update:value', (e.target as HTMLInputElement).value)"
      />
      <span v-if="suffix" class="text-sm text-muted-foreground">{{ suffix }}</span>
    </div>
  </SettingsFieldBase>
</template>

<script lang="ts">
export default {
  name: 'SettingsFieldInput',
  props: {
    title: { type: String, required: true },
    description: { type: String, required: true },
    value: { type: [String, Number], default: '' },
    type: { type: String, default: 'text' },
    min: { type: Number, default: undefined },
    max: { type: Number, default: undefined },
    placeholder: { type: String, default: '' },
    inputClass: { type: String, default: '' },
    suffix: { type: String, default: '' },
    layout: { type: String as () => 'horizontal' | 'vertical', default: 'vertical' },
  },
  emits: ['update:value'],
};
</script>

// packages/reactui/src/pages/settings/components/fields/SettingsFieldInput.tsx
import { Input } from "@/components/ui/input"
import { SettingsFieldBase } from "./SettingsFieldBase"

type SettingsFieldInputProps = {
    title: string
    description: string
    value: string | number
    onChange: (value: string) => void
    type?: string
    min?: number
    max?: number
    placeholder?: string
    className?: string
    suffix?: string
    layout?: "horizontal" | "vertical"
}

/**
 * Settings field component for text and numeric input values.
 * Supports various input types, validation ranges, and optional suffix.
 * Uses vertical layout by default to accommodate longer inputs.
 */
export function SettingsFieldInput({
    title,
    description,
    value,
    onChange,
    type = "text",
    min,
    max,
    placeholder,
    className,
    suffix,
    layout = "vertical"
}: SettingsFieldInputProps) {
    const inputElement = (
        <div 
            className="flex items-center gap-3"
            data-component="settings-input-wrapper"
        >
            <Input
                type={type}
                min={min}
                max={max}
                value={value}
                onChange={(e) => onChange(e.target.value)}
                placeholder={placeholder}
                className={className}
                data-component="settings-input-control"
                data-input-type={type}
            />
            {suffix && (
                <span 
                    className="text-sm text-muted-foreground"
                    data-component="settings-input-suffix"
                >
                    {suffix}
                </span>
            )}
        </div>
    )

    return (
        <div data-component="settings-field-input">
            <SettingsFieldBase title={title} description={description} layout={layout}>
                {inputElement}
            </SettingsFieldBase>
        </div>
    )
}

SettingsFieldInput.displayName = "SettingsFieldInput"
