// vueui/src/components/settings/SettingsFieldSelect.vue
<script setup lang="ts">
import Select from '@/components/ui/Select.vue';
import SelectItem from '@/components/ui/SelectItem.vue';
import SettingsFieldBase from './SettingsFieldBase.vue';

defineProps<{
  title: string;
  description: string;
  modelValue: string;
  options: { value: string; label: string }[];
  placeholder?: string;
  selectClass?: string;
  layout?: 'horizontal' | 'vertical';
}>();

defineEmits<{
  'update:modelValue': [value: string];
}>();
</script>

<template>
  <SettingsFieldBase
    :title="title"
    :description="description"
    :layout="layout ?? 'vertical'"
  >
    <Select
      :model-value="modelValue"
      :placeholder="placeholder ?? 'Select option'"
      :class="selectClass ?? 'w-[300px]'"
      @update:model-value="$emit('update:modelValue', $event)"
    >
      <SelectItem
        v-for="opt in options"
        :key="opt.value"
        :value="opt.value"
      >
        {{ opt.label }}
      </SelectItem>
    </Select>
  </SettingsFieldBase>
</template>

// packages/reactui/src/pages/settings/components/fields/SettingsFieldSelect.tsx
import { 
    Select, 
    SelectContent, 
    SelectItem, 
    SelectTrigger, 
    SelectValue 
} from "@/components/ui/select"
import { SettingsFieldBase } from "./SettingsFieldBase"

type SelectOption = {
    value: string
    label: string
}

type SettingsFieldSelectProps = {
    title: string
    description: string
    value: string
    onValueChange: (value: string) => void
    options: SelectOption[]
    placeholder?: string
    className?: string
    layout?: "horizontal" | "vertical"
}

/**
 * Settings field component for dropdown/select values.
 * Renders a select control with customizable options and placeholder.
 * Uses vertical layout by default to accommodate dropdown expansion.
 */
export function SettingsFieldSelect({
    title,
    description,
    value,
    onValueChange,
    options,
    placeholder = "Select option",
    className = "w-[300px]",
    layout = "vertical"
}: SettingsFieldSelectProps) {
    const selectElement = (
        <Select 
            value={value} 
            onValueChange={onValueChange}
            data-component="settings-select-control"
        >
            <SelectTrigger className={className}>
                <SelectValue placeholder={placeholder} />
            </SelectTrigger>
            <SelectContent data-component="settings-select-dropdown">
                {options.map(option => (
                    <SelectItem 
                        key={option.value} 
                        value={option.value}
                        data-component="settings-select-option"
                        data-value={option.value}
                    >
                        {option.label}
                    </SelectItem>
                ))}
            </SelectContent>
        </Select>
    )

    return (
        <div data-component="settings-field-select">
            <SettingsFieldBase title={title} description={description} layout={layout}>
                {selectElement}
            </SettingsFieldBase>
        </div>
    )
}

SettingsFieldSelect.displayName = "SettingsFieldSelect"
