// packages/reactui/src/pages/settings/components/layout/SettingsSectionItem.tsx
import type { ReactNode } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"

type SettingsSectionItemProps = {
    title: string
    description: string
    icon?: ReactNode
    children: ReactNode
}

/**
 * Individual settings section component.
 * Renders a card with title, description, optional icon, and content area.
 * Designed to contain one or more settings field components.
 */
export function SettingsSectionItem({ 
    title, 
    description, 
    icon, 
    children 
}: SettingsSectionItemProps) {
    return (
        <Card data-component="settings-section-item" className="bg-base-200">
            <CardHeader data-component="settings-section-header">
                <CardTitle 
                    className="flex items-center gap-2"
                    data-component="settings-section-title"
                >
                    {icon && (
                        <span data-component="settings-section-icon">
                            {icon}
                        </span>
                    )}
                    {title}
                </CardTitle>
                <CardDescription data-component="settings-section-description">
                    {description}
                </CardDescription>
            </CardHeader>
            <CardContent 
                className="space-y-4"
                data-component="settings-section-content"
            >
                {children}
            </CardContent>
        </Card>
    )
}

SettingsSectionItem.displayName = "SettingsSectionItem"

// vueui/src/components/settings/SettingsSectionItem.vue
<script setup lang="ts">
import Card from '@/components/ui/Card.vue';
import CardHeader from '@/components/ui/CardHeader.vue';
import CardTitle from '@/components/ui/CardTitle.vue';
import CardDescription from '@/components/ui/CardDescription.vue';
import CardContent from '@/components/ui/CardContent.vue';
</script>

<template>
  <Card class="bg-base-200">
    <CardHeader>
      <CardTitle class="flex items-center gap-2">
        <slot name="icon" />
        {{ title }}
      </CardTitle>
      <CardDescription>{{ description }}</CardDescription>
    </CardHeader>
    <CardContent class="space-y-4">
      <slot />
    </CardContent>
  </Card>
</template>

<script lang="ts">
export default {
  name: 'SettingsSectionItem',
  props: {
    title: { type: String, required: true },
    description: { type: String, required: true },
  },
};
</script>
