// packages/vueui/src/components/MonacoEditor/MonacoEditor.vue
<script setup lang="ts">
import { computed } from 'vue';
import { VueMonacoEditor } from '@guolao/vue-monaco-editor';
import { getThemeInfo } from '@/lib/themes';

const props = withDefaults(
  defineProps<{
    modelValue: string;
    language?: string;
    theme?: string;
    height?: string;
    readOnly?: boolean;
  }>(),
  {
    language: 'json',
    theme: 'default',
    height: '100%',
    readOnly: true,
  }
);

defineEmits<{ 'update:modelValue': [value: string] }>();

const monacoTheme = computed(() => {
  const info = getThemeInfo(props.theme);
  return info.isDarkTheme ? 'vs-dark' : 'vs';
});

const editorOptions = {
  minimap: { enabled: false },
  scrollBeyondLastLine: false,
  fontSize: 14,
  lineNumbers: 'on' as const,
  roundedSelection: false,
  automaticLayout: true,
  readOnly: props.readOnly,
};
</script>

<template>
  <VueMonacoEditor
    :value="modelValue"
    :language="language"
    :theme="monacoTheme"
    :height="height"
    :options="editorOptions"
    @change="(value: string | undefined) => $emit('update:modelValue', value ?? '')"
  >
    <template #default>Loading editor…</template>
  </VueMonacoEditor>
</template>

// packages/reactui/src/components/MonacoEditor/MonacoEditor.tsx
import React from 'react';
import Editor from '@monaco-editor/react';

interface MonacoEditorProps {
    value: string;
    language?: string;
    theme?: string;
    height?: string;
    readOnly?: boolean;
    onChange?: (value: string | undefined) => void;
    options?: any;
}

const MonacoEditor: React.FC<MonacoEditorProps> = ({
    value,
    language = 'json',
    theme = 'vs-dark',
    height = '400px',
    readOnly = false,
    onChange,
    options = {}
}) => {
    const defaultOptions = {
        minimap: { enabled: false },
        scrollBeyondLastLine: false,
        fontSize: 14,
        lineNumbers: 'on',
        roundedSelection: false,
        automaticLayout: true,
        readOnly,
        ...options
    };

    return (
        <Editor
            height={height}
            language={language}
            theme={theme}
            value={value}
            onChange={onChange}
            options={defaultOptions}
        />
    );
};

export default MonacoEditor;
