// packages/studio/src/components/sidebar/SidebarItem.vue
<template>
    <li @click="select" :class="`sidebar-border ${props.selected ? 'sidebar-item-selected' : ''}`">
        <RouterLink :class="`sidebar-item`" :to="props.path">
            <i :class="`bi ${props.icon}`"></i>
        </RouterLink>
    </li>
</template>

<script setup lang="ts">
    import {defineEmits} from "vue"

    const emit = defineEmits(['item-selected'])

    const props = defineProps<{
        id: number,
        selected?: boolean
        path: string,
        icon: string
    }>()

    function select() {
        emit('item-selected', props.id)
    }

</script>

<style scoped lang="postcss">
.sidebar-item {
    @apply flex items-center text-4xl py-4 px-2 h-12 overflow-hidden text-ellipsis whitespace-nowrap hover:rounded-r hover:text-gray-900 hover:bg-gray-100 transition duration-300 ease-in-out
}
.sidebar-border {
    @apply border-l-2 border-l-transparent
}
.sidebar-item-selected {
    @apply border-opacity-80 border-l-primary
}
</style>

// packages/reactui/src/components/sidebar/SidebarItem.tsx
import type { IconType } from 'react-icons';
import { Link } from 'react-router-dom';

import {
    Tooltip,
    TooltipContent,
    TooltipTrigger,
} from '@/components/ui/tooltip';
import { cn } from '@/lib/utils';

interface SidebarItemProps {
    name: string;
    path: string;
    icon: IconType;
    selected?: boolean;
}

export function SidebarItem({
    name,
    path,
    icon: Icon,
    selected,
}: SidebarItemProps) {
    return (
        <li
            className={cn(
                'border-l-2 border-l-transparent',
                selected && 'border-l-primary'
            )}
        >
            <Tooltip>
                <TooltipTrigger asChild>
                    <Link
                        to={path}
                        className={cn(
                            'flex items-center text-4xl py-4 px-2 h-12 overflow-hidden text-ellipsis whitespace-nowrap text-sidebar-foreground',
                            'hover:rounded-r hover:bg-sidebar-accent hover:text-sidebar-accent-foreground transition duration-300 ease-in-out'
                        )}
                    >
                        <Icon />
                    </Link>
                </TooltipTrigger>
                <TooltipContent side="right">
                    <p>{name}</p>
                </TooltipContent>
            </Tooltip>
        </li>
    );
}
