// packages/vueui/src/components/SidebarItem.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router';
import Tooltip from '@/components/ui/Tooltip.vue';
import { cn } from '@/lib/utils';

const props = withDefaults(
  defineProps<{ path: string; name: string; selected?: boolean }>(),
  { selected: false }
);

function getTo(path: string) {
  return path;
}
</script>

<template>
  <div
    :class="cn(
      'border-l-4 border-l-transparent',
      props.selected && 'border-l-primary'
    )"
  >
    <Tooltip side="right">
      <template #trigger>
        <RouterLink
          :to="getTo(props.path)"
          :class="cn(
            'flex items-center justify-center py-4 px-2 h-12 overflow-hidden text-ellipsis whitespace-nowrap text-base-foreground/80',
            'hover:bg-base-300 hover:text-base-foreground transition duration-300 ease-in-out',
            props.selected && 'bg-primary/10 text-base-foreground'
          )"
        >
          <slot name="icon">
            <span class="text-lg font-semibold">{{ name.charAt(0) }}</span>
          </slot>
        </RouterLink>
      </template>
      <template #default>
        <p>{{ props.name }}</p>
      </template>
    </Tooltip>
  </div>
</template>

// packages/reactui/src/components/sidebar/SidebarItem.tsx
import type { IconType } from 'react-icons';
import { Link } from '@/keepaliverouter';

import {
    Tooltip,
    TooltipContent,
    TooltipTrigger,
} from '@/components/ui/tooltip';
import { cn } from '@/lib/utils';
import { memo } from 'react';

interface SidebarItemProps {
    name: string;
    path: string;
    icon: IconType;
    selected?: boolean;
}

export const SidebarItem = memo(({
    name,
    path,
    icon: Icon,
    selected,
}: SidebarItemProps) => {
    return (
        <div
            className={cn(
                'border-l-4 border-l-transparent',
                selected && 'border-l-primary'
            )}
        >
            <Tooltip>
                <TooltipTrigger asChild>
                    <Link
                        to={path}
                        className={cn(
                            'flex items-center text-4xl py-4 px-2 h-12 overflow-hidden text-ellipsis whitespace-nowrap text-sidebar-foreground',
                            'hover:bg-base-300 hover:text-base-foreground transition duration-300 ease-in-out',
                            selected && 'bg-primary/10'
                        )}
                    >
                        <Icon />
                    </Link>
                </TooltipTrigger>
                <TooltipContent side="right">
                    <p>{name}</p>
                </TooltipContent>
            </Tooltip>
        </div>
    );
})

SidebarItem.displayName = 'SidebarItem';
