// packages/vueui/src/components/Sidebar.vue
<script setup lang="ts">
import { useRoute } from 'vue-router';
import { computed } from 'vue';
import {
  FolderOpen,
  Code2,
  Smartphone,
  Rocket,
  Settings,
} from 'lucide-vue-next';
import SidebarItem from './SidebarItem.vue';
import { cn } from '@/lib/utils';

const route = useRoute();

function isPathPrefix(prefix: string, path: string): boolean {
  if (prefix === path) return true;
  const normalized = path.endsWith('/') ? path.slice(0, -1) : path;
  const prefixNorm = prefix.endsWith('/') ? prefix : prefix + '/';
  return normalized === prefix || normalized.startsWith(prefixNorm);
}

const currentPath = computed(() => route.path);

function isActive(path: string): boolean {
  if (path === '/editor') {
    return currentPath.value === '/' || isPathPrefix('/editor', currentPath.value);
  }
  return isPathPrefix(path, currentPath.value);
}
</script>

<template>
  <aside
    :class="cn(
      'shadow-md pl-0 bg-base-200 w-[56px] flex-shrink-0 h-screen border-r border-base-300'
    )"
  >
    <div class="flex flex-col h-full">
      <div class="flex-1">
        <div class="align-middle p-2 h-12 flex items-center justify-center">
          <span class="text-xl font-bold text-primary">ZK</span>
        </div>
        <SidebarItem path="/projects" name="Projects" :selected="isActive('/projects')">
          <template #icon><FolderOpen class="size-6" /></template>
        </SidebarItem>
        <SidebarItem path="/editor" name="Editor" :selected="isActive('/editor')">
          <template #icon><Code2 class="size-6" /></template>
        </SidebarItem>
        <SidebarItem path="/devices" name="Devices" :selected="isActive('/devices')">
          <template #icon><Smartphone class="size-6" /></template>
        </SidebarItem>
        <SidebarItem path="/exporter" name="Export" :selected="isActive('/exporter')">
          <template #icon><Rocket class="size-6" /></template>
        </SidebarItem>
      </div>
      <div>
        <SidebarItem path="/settings" name="Settings" :selected="isActive('/settings')">
          <template #icon><Settings class="size-6" /></template>
        </SidebarItem>
      </div>
    </div>
  </aside>
</template>

// packages/reactui/src/components/sidebar/Sidebar.tsx
import {
    BsJournals as JournalCodeIcon,
    BsPhone as PhoneIcon,
    BsBoxSeam as BoxesIcon,
    BsGear as GearIcon,
} from 'react-icons/bs';
import { useLocation } from 'react-router-dom';

import { Logo } from '../logo/Logo';

import { SidebarItem } from './SidebarItem';

import { cn } from '@/lib/utils';

export function Sidebar() {
    const location = useLocation();
    const pathname = location.pathname;

    // Helper function to check if a route is active
    const isRouteActive = (path: string) => {
        if (path === '/editor') {
            return pathname === '/editor' || pathname === '/';
        }
        return pathname === path;
    };

    return (
        <aside
            className={cn(
                'shadow-md pl-0 bg-sidebar max-w-[56px] max-h-screen h-screen'
            )}
        >
            <div className="flex flex-col h-full">
                <div className="flex-1">
                    <div className="align-middle p-2 h-12">
                        <Logo />
                    </div>
                    <SidebarItem
                        path="/editor"
                        name="Editor"
                        selected={isRouteActive('/editor')}
                        icon={JournalCodeIcon}
                    />
                    <SidebarItem
                        path="/devices"
                        name="Devices"
                        selected={isRouteActive('/devices')}
                        icon={PhoneIcon}
                    />
                    <SidebarItem
                        path="/exporter"
                        name="Export"
                        selected={isRouteActive('/exporter')}
                        icon={BoxesIcon}
                    />
                </div>
                <div>
                    <SidebarItem
                        path="/settings"
                        name="Settings"
                        selected={isRouteActive('/settings')}
                        icon={GearIcon}
                    />
                </div>
            </div>
        </aside>
    );
}
