// packages/nestui/src/components/sidebar/Sidebar.vue
<template>
    <div class="sidebar">
        <div class="flex flex-col h-full">
            <div class="flex-1">
                <div class="align-middle p-2 h-12">
                    <Logo />
                </div>
                <SidebarItem
                    :id="0"
                    path="/editor"
                    name="Editor"
                    :selected="routeName === 'editor'"
                    icon="bi-journal-code"
                />
                <SidebarItem
                    :id="1"
                    path="/devices"
                    name="Devices"
                    :selected="routeName === 'devices'"
                    icon="bi-phone"
                />
                <SidebarItem
                    :id="2"
                    path="/exporter"
                    name="Export"
                    :selected="routeName === 'exporter'"
                    icon="bi-boxes"
                />
            </div>
            <div>
                <SidebarItem
                    :id="2"
                    name="Settings"
                    path="/settings"
                    :selected="routeName === 'settings'"
                    icon="bi-gear"
                />
            </div>
        </div>
    </div>
</template>

<script setup>
import SidebarItem from "@nestui/components/sidebar/SidebarItem.vue"
import {computed} from "vue"
import {useRoute} from "vue-router"
import Logo from "@nestui/components/Logo.vue"

const router = useRoute()

const routeName = computed(() => router.name)

</script>

<style scoped lang="postcss">
.sidebar {
    @apply shadow-md pl-0 px-1 bg-base-300 max-w-[56px] max-h-screen h-screen
}

</style>

// packages/reactui/src/components/sidebar/Sidebar.tsx
import {
    BsJournals as JournalCodeIcon,
    BsPhone as PhoneIcon,
    BsBoxSeam as BoxesIcon,
    BsGear as GearIcon,
} from 'react-icons/bs';
import { useLocation } from 'react-router-dom';

import { Logo } from '../logo/Logo';

import { SidebarItem } from './SidebarItem';

import { cn } from '@/lib/utils';

export function Sidebar() {
    const location = useLocation();
    const pathname = location.pathname;

    // Helper function to check if a route is active
    const isRouteActive = (path: string) => {
        if (path === '/editor') {
            return pathname === '/editor' || pathname === '/';
        }
        return pathname === path;
    };

    return (
        <aside
            className={cn(
                'shadow-md pl-0 bg-sidebar max-w-[56px] max-h-screen h-screen'
            )}
        >
            <div className="flex flex-col h-full">
                <div className="flex-1">
                    <div className="align-middle p-2 h-12">
                        <Logo />
                    </div>
                    <SidebarItem
                        path="/editor"
                        name="Editor"
                        selected={isRouteActive('/editor')}
                        icon={JournalCodeIcon}
                    />
                    <SidebarItem
                        path="/devices"
                        name="Devices"
                        selected={isRouteActive('/devices')}
                        icon={PhoneIcon}
                    />
                    <SidebarItem
                        path="/exporter"
                        name="Export"
                        selected={isRouteActive('/exporter')}
                        icon={BoxesIcon}
                    />
                </div>
                <div>
                    <SidebarItem
                        path="/settings"
                        name="Settings"
                        selected={isRouteActive('/settings')}
                        icon={GearIcon}
                    />
                </div>
            </div>
        </aside>
    );
}
