// packages/reactui/src/providers/Electron/ElectronProvider.tsx
import { createContext, useCallback, useRef, type ReactNode, useEffect } from 'react'
import type { ElectronSubscription } from '../../types/electron'

interface ElectronProviderState {
    onLoadZko: (callback: (data: any) => void) => void
    onImportFile: (callback: (data: any) => void) => void
    onBundleScene: (callback: (data: any) => void) => void
    onCreateProject: (callback: () => void) => void
    onOpenProject: (callback: (data: { filePath: string }) => void) => void
    offLoadZko: () => void
    offImportFile: () => void
    offBundleScene: () => void
    offCreateProject: () => void
    offOpenProject: () => void
    isElectron: boolean
}

const initialState: ElectronProviderState = {
    onLoadZko: () => null,
    onImportFile: () => null,
    onBundleScene: () => null,
    onCreateProject: () => null,
    onOpenProject: () => null,
    offLoadZko: () => null,
    offImportFile: () => null,
    offBundleScene: () => null,
    offCreateProject: () => null,
    offOpenProject: () => null,
    isElectron: false
}

const ElectronProviderContext = createContext<ElectronProviderState>(initialState)

const isElectron = typeof window !== 'undefined' && window.NativeZernikalos !== undefined

export function ElectronProvider({ children, ...props }: { children: ReactNode }) {
    const subscriptions = useRef<Map<string, ElectronSubscription>>(new Map())

    const onLoadZko = useCallback((callback: (data: any) => void) => {
        if (isElectron && !subscriptions.current.has('loadZko')) {
            console.log("🔄 ElectronProvider - Registering LoadZko callback")
            const subscription = window.NativeZernikalos?.handleLoadZko((ev: any, data: any) => {
                console.log("📁 LoadZko callback triggered", { ev, data })
                callback(data)
            })
            if (subscription) {
                subscriptions.current.set('loadZko', subscription)
            }
        }
    }, [])

    const onImportFile = useCallback((callback: (data: any) => void) => {
        if (isElectron && !subscriptions.current.has('importFile')) {
            console.log("🔄 ElectronProvider - Registering ImportFile callback")
            const subscription = window.NativeZernikalos?.handleShowImport((ev: any, data: any) => {
                console.log("📁 ImportFile callback triggered", { ev, data })
                callback(data)
            })
            if (subscription) {
                subscriptions.current.set('importFile', subscription)
            }
        }
    }, [])

    const onBundleScene = useCallback((callback: (data: any) => void) => {
        if (isElectron && !subscriptions.current.has('bundleScene')) {
            console.log("🔄 ElectronProvider - Registering BundleScene callback")
            const subscription = window.NativeZernikalos?.handleBundleScene((ev: any, data: any) => {
                console.log("📦 BundleScene callback triggered", { ev, data })
                callback(data)
            })
            if (subscription) {
                subscriptions.current.set('bundleScene', subscription)
            }
        }
    }, [])

    const offLoadZko = useCallback(() => {
        const subscription = subscriptions.current.get('loadZko')
        subscription?.off()
        subscriptions.current.delete('loadZko')
        console.log("🔄 ElectronProvider - Removed LoadZko callback")
    }, [])

    const offImportFile = useCallback(() => {
        const subscription = subscriptions.current.get('importFile')
        subscription?.off()
        subscriptions.current.delete('importFile')
        console.log("🔄 ElectronProvider - Removed ImportFile callback")
    }, [])

    const offBundleScene = useCallback(() => {
        const subscription = subscriptions.current.get('bundleScene')
        subscription?.off()
        subscriptions.current.delete('bundleScene')
        console.log("🔄 ElectronProvider - Removed BundleScene callback")
    }, [])

    const onCreateProject = useCallback((callback: () => void) => {
        if (isElectron && !subscriptions.current.has('createProject')) {
            console.log("🔄 ElectronProvider - Registering CreateProject callback")
            const subscription = window.NativeZernikalos?.handleCreateProject?.((ev: any) => {
                console.log("📁 CreateProject callback triggered", { ev })
                callback()
            })
            if (subscription) {
                subscriptions.current.set('createProject', subscription)
            }
        }
    }, [])

    const offCreateProject = useCallback(() => {
        const subscription = subscriptions.current.get('createProject')
        subscription?.off()
        subscriptions.current.delete('createProject')
        console.log("🔄 ElectronProvider - Removed CreateProject callback")
    }, [])

    const onOpenProject = useCallback((callback: (data: { filePath: string }) => void) => {
        if (isElectron && !subscriptions.current.has('openProject')) {
            console.log("🔄 ElectronProvider - Registering OpenProject callback")
            const subscription = window.NativeZernikalos?.handleOpenProject?.((ev: any, data: any) => {
                console.log("📁 OpenProject callback triggered", { ev, data })
                callback(data)
            })
            if (subscription) {
                subscriptions.current.set('openProject', subscription)
            }
        }
    }, [])

    const offOpenProject = useCallback(() => {
        const subscription = subscriptions.current.get('openProject')
        subscription?.off()
        subscriptions.current.delete('openProject')
        console.log("🔄 ElectronProvider - Removed OpenProject callback")
    }, [])

    // Cleanup cuando se desmonta el provider
    useEffect(() => {
        return () => {
            offLoadZko()
            offImportFile()
            offBundleScene()
            offCreateProject()
            offOpenProject()
        }
    }, [offLoadZko, offImportFile, offBundleScene, offCreateProject, offOpenProject])

    const value: ElectronProviderState = {
        onLoadZko,
        onImportFile,
        onBundleScene,
        onCreateProject,
        onOpenProject,
        offLoadZko,
        offImportFile,
        offBundleScene,
        offCreateProject,
        offOpenProject,
        isElectron
    }

    return (
        <ElectronProviderContext.Provider {...props} value={value}>
            {children}
        </ElectronProviderContext.Provider>
    )
}

// Export the context for use in the hook
export { ElectronProviderContext }

// vueui/src/components/ElectronProvider.vue
<script setup lang="ts">
import { provide, ref, onUnmounted } from 'vue';
import type { ElectronSubscription } from '@/types/electron';

const isElectron =
  typeof window !== 'undefined' && window.NativeZernikalos !== undefined;

const subscriptions = new Map<string, ElectronSubscription>();

function off(name: string) {
  const sub = subscriptions.get(name);
  sub?.off();
  subscriptions.delete(name);
}

function onLoadZko(cb: (data: unknown) => void) {
  if (!isElectron || subscriptions.has('loadZko')) return;
  const sub = window.NativeZernikalos?.handleLoadZko?.((_ev, data) => cb(data));
  if (sub) subscriptions.set('loadZko', sub);
}

function onImportFile(cb: (data: unknown) => void) {
  if (!isElectron || subscriptions.has('importFile')) return;
  const sub = window.NativeZernikalos?.handleShowImport?.((_ev, data) => cb(data));
  if (sub) subscriptions.set('importFile', sub);
}

function onBundleScene(cb: () => void) {
  if (!isElectron || subscriptions.has('bundleScene')) return;
  const sub = window.NativeZernikalos?.handleBundleScene?.(() => cb());
  if (sub) subscriptions.set('bundleScene', sub);
}

function onCreateProject(cb: () => void) {
  if (!isElectron || subscriptions.has('createProject')) return;
  const sub = window.NativeZernikalos?.handleCreateProject?.(() => cb());
  if (sub) subscriptions.set('createProject', sub);
}

function onOpenProject(cb: (data: { filePath: string }) => void) {
  if (!isElectron || subscriptions.has('openProject')) return;
  const sub = window.NativeZernikalos?.handleOpenProject?.((_ev, data: { filePath: string }) => cb(data));
  if (sub) subscriptions.set('openProject', sub);
}

const api = ref({
  isElectron,
  onLoadZko,
  onImportFile,
  onBundleScene,
  onCreateProject,
  onOpenProject,
  offLoadZko: () => off('loadZko'),
  offImportFile: () => off('importFile'),
  offBundleScene: () => off('bundleScene'),
  offCreateProject: () => off('createProject'),
  offOpenProject: () => off('openProject'),
});

provide('electron', api);

onUnmounted(() => {
  off('loadZko');
  off('importFile');
  off('bundleScene');
  off('createProject');
  off('openProject');
});
</script>

<template>
  <slot />
</template>
