// packages/reactui/src/components/MonacoEditor/MonacoEditor.tsx
import React, { useEffect } from 'react';
import Editor from '@monaco-editor/react';
import { type Theme } from '../../lib/themes';
import oceanicNextTheme from './themes/oceanic-next.json';

interface MonacoEditorProps {
    value: string;
    language?: string;
    theme?: Theme; // Our app theme name
    height?: string;
    readOnly?: boolean;
    onChange?: (value: string | undefined) => void;
    options?: any;
}

// Function to transform our themes to Monaco themes
const transformThemeToMonaco = (appTheme: Theme): string => {
    const themeMap: Record<Theme, string> = {
        'default': 'vs',           // Light theme
        'default-dark': 'vs-dark', // Dark theme
        'ocean': 'oceanic-next',   // Custom Ocean theme
        'forest': 'vs-dark',       // Forest is dark
        'sunset': 'vs-dark',       // Sunset is dark
        'purple': 'vs-dark',       // Purple is dark
        'rose': 'vs-dark'          // Rose is dark
    };
    
    return themeMap[appTheme] || 'vs-dark';
};

// Function to register custom themes with Monaco
const registerCustomThemes = (monaco: any) => {
    // Register the Oceanic Next theme
    monaco.editor.defineTheme('oceanic-next', oceanicNextTheme as any);
};

export const MonacoEditor: React.FC<MonacoEditorProps> = ({
    value,
    language = 'json',
    theme = 'default-dark', // Default to dark theme
    height = '400px',
    readOnly = false,
    onChange,
    options = {}
}) => {
    // Transform our theme to Monaco theme
    const monacoTheme = transformThemeToMonaco(theme);
    
    const defaultOptions = {
        minimap: { enabled: false },
        scrollBeyondLastLine: false,
        fontSize: 14,
        lineNumbers: 'on',
        roundedSelection: false,
        automaticLayout: true,
        readOnly,
        ...options
    };

    return (
        <Editor
            data-component="MonacoEditor"
            height={height}
            language={language}
            theme={monacoTheme}
            value={value}
            onChange={onChange}
            options={defaultOptions}
            beforeMount={registerCustomThemes}
        />
    );
};

// vueui/src/components/MonacoEditor/MonacoEditor.vue
<script setup lang="ts">
import { computed } from 'vue';
import { VueMonacoEditor } from '@guolao/vue-monaco-editor';
import { getThemeInfo } from '@/lib/themes';
import oceanicNextTheme from './themes/oceanic-next.json';

const props = withDefaults(
  defineProps<{
    modelValue: string;
    language?: string;
    theme?: string;
    height?: string;
    readOnly?: boolean;
    options?: Record<string, unknown>;
  }>(),
  {
    language: 'json',
    theme: 'default',
    height: '100%',
    readOnly: true,
    options: () => ({}),
  }
);

const emit = defineEmits<{
  'update:modelValue': [value: string];
  change: [value: string | undefined, event: unknown];
  validate: [markers: unknown];
  mount: [editor: unknown, monaco: unknown];
}>();

const monacoTheme = computed(() => {
  const themeMap: Record<string, string> = {
    default: 'vs',
    'default-dark': 'vs-dark',
    ocean: 'oceanic-next',
    forest: 'vs-dark',
    sunset: 'vs-dark',
    purple: 'vs-dark',
    rose: 'vs-dark',
  };

  const mapped = themeMap[props.theme];
  if (mapped) return mapped;

  const info = getThemeInfo(props.theme);
  return info.isDarkTheme ? 'vs-dark' : 'vs';
});

const editorOptions = computed(() => ({
  minimap: { enabled: false },
  scrollBeyondLastLine: false,
  fontSize: 14,
  lineNumbers: 'on' as const,
  roundedSelection: false,
  automaticLayout: true,
  readOnly: props.readOnly,
  ...(props.options ?? {}),
}));

const handleBeforeMount = (monaco: any) => {
  // Register custom themes for Monaco usage.
  monaco.editor.defineTheme('oceanic-next', oceanicNextTheme as any);
};

const handleChange = (value: string | undefined, event: unknown) => {
  emit('update:modelValue', value ?? '');
  emit('change', value, event);
};
</script>

<template>
  <VueMonacoEditor
    :value="modelValue"
    :language="language"
    :theme="monacoTheme"
    :height="height"
    :options="editorOptions"
    @beforeMount="handleBeforeMount"
    @mount="(editor, monaco) => emit('mount', editor, monaco)"
    @validate="(markers) => emit('validate', markers)"
    @change="handleChange"
  >
    <template #default>Loading editor…</template>
  </VueMonacoEditor>
</template>
