// packages/reactui/src/components/ui/separator.tsx
'use client';

import * as SeparatorPrimitive from '@radix-ui/react-separator';
import * as React from 'react';

import { cn } from '@/lib/utils';

function Separator({
    className,
    orientation = 'horizontal',
    decorative = true,
    ...props
}: React.ComponentProps<typeof SeparatorPrimitive.Root>) {
    return (
        <SeparatorPrimitive.Root
            data-slot="separator"
            decorative={decorative}
            orientation={orientation}
            className={cn(
                'bg-base-300 shrink-0 data-[orientation=horizontal]:h-px data-[orientation=horizontal]:w-full data-[orientation=vertical]:h-full data-[orientation=vertical]:w-px',
                className
            )}
            {...props}
        />
    );
}

export { Separator };

// vueui/src/components/ui/Separator.vue
<script setup lang="ts">
import { Separator } from 'radix-vue';
import { cn } from '@/lib/utils';

const props = withDefaults(
  defineProps<{ class?: string; orientation?: 'horizontal' | 'vertical'; decorative?: boolean }>(),
  { orientation: 'horizontal', decorative: true }
);
</script>

<template>
  <Separator
    data-slot="separator"
    :decorative="props.decorative"
    :orientation="props.orientation"
    :class="
      cn(
        'shrink-0 bg-base-300 data-[orientation=horizontal]:h-px data-[orientation=horizontal]:w-full data-[orientation=vertical]:h-full data-[orientation=vertical]:w-px',
        props.class
      )
    "
  />
</template>
