// packages/studio/src/layouts/MainLayout.vue
<template>
    <div class="flex flex-col h-screen">
        <Navbar class="h-[5%] min-h-12 max-h-12"></Navbar>
        <div class="flex h-[96%]">
            <Sidebar></Sidebar>
            <RouterView id="router-view" class="wrapper"/>
        </div>
    </div>
</template>

<script setup lang="ts">
import {RouterView} from "vue-router";
import Navbar from "@studio/components/Navbar.vue"
import Sidebar from "@studio/components/sidebar/Sidebar.vue"
</script>

<style scoped>
.wrapper {
    @apply mt-5 pr-0 pb-0
}

</style>

// packages/reactui/src/layouts/MainLayout.tsx
import { KeepAliveOutlet } from '@/keepaliverouter';
import { Sidebar } from '@/components/sidebar/Sidebar';
import { useElectronProjectIntegration } from '@/hooks/useElectronProjectIntegration';

export function MainLayout() {
    // Initialize Electron integration here, after KeepAliveRouterProvider is available
    useElectronProjectIntegration()
    
    return (
        <div className="h-screen">
            <div className="grid h-screen">
                <div className="grid grid-rows-1 grid-cols-[56px_minmax(0,1fr)] max-h-screen">
                    <Sidebar />
                    <main id="router-view" className="flex flex-col">
                        <KeepAliveOutlet className="flex-1" />
                    </main>
                </div>
            </div>
        </div>
    );
}
