// packages/nestui/src/views/NewProject.vue
<template>
    <div class="flex h-full justify-center items-center">
        <Button variant="solid" color="info" @click="createNewProject">
            New Project
        </Button>
    </div>
</template>

<script setup lang="ts">
import Button from "@nestui/components/Button.vue"
import { useProjectStore } from "../store/projectStore";

const projectStore = useProjectStore()

function createNewProject() {
    projectStore.createProject()
}
</script>

<style scoped>

</style>

// packages/reactui/src/views/editor/NewProject.tsx
import React from 'react';

import { Button } from '@/components/ui/button';

interface NewProjectProps {
    onNewProject: () => void;
}

const NewProject: React.FC<NewProjectProps> = ({ onNewProject }) => {
    return (
        <div className="flex h-full justify-center items-center">
            <Button variant="default" onClick={onNewProject}>
                New Project
            </Button>
        </div>
    );
};

export default NewProject;
