// packages/reactui/src/pages/ExporterPage.tsx
import React from 'react';


interface ExporterPageProps {}

export const ExporterPage: React.FC<ExporterPageProps> = () => {

    return (
        <div className="p-6 max-w-7xl mx-auto">
            <h1 className="text-2xl font-bold">Export Page</h1>
            <p className="text-gray-600">This is a placeholder for the export page.</p>
        </div>
    );
};

// vueui/src/views/ExporterPage.vue
<script setup lang="ts">
defineOptions({ name: 'ExporterPage' });
</script>

<template>
  <div class="p-6 max-w-7xl mx-auto">
    <h1 class="text-2xl font-bold">Export Page</h1>
    <p class="text-muted-foreground mt-2">
      Export your scene for production (placeholder).
    </p>
  </div>
</template>
